//! Conformance-vector replay tests. Vectors are generated by `just vectors`
//! (tools/gen_vectors.zig) and checked in; this runner re-derives every
//! result and byte-compares. Skips cleanly when vectors/ is absent
//! (pre-first-generation bootstrap).

const std = @import("std");
const slcp = @import("slcp-core");

fn readVector(gpa: std.mem.Allocator, comptime name: []const u8) ?[]u8 {
    const io = std.testing.io;
    return std.Io.Dir.cwd().readFileAlloc(io, "vectors/" ++ name, gpa, .unlimited) catch null;
}

test "vectors placeholder: generation lands in this milestone" {
    const gpa = std.testing.allocator;
    if (readVector(gpa, "crypto.json")) |bytes| {
        gpa.free(bytes);
    } else {
        return error.SkipZigTest;
    }
}
