//! Conformance-vector replay tests (design §13.4). Vectors are generated by
//! `just vectors` (tools/gen_vectors.zig) and checked in; this runner parses
//! the JSON and RE-DERIVES every result through slcp-core, byte-comparing.
//! Tests skip (error.SkipZigTest) when vectors/ is absent (pre-first-
//! generation bootstrap). The differential test additionally shells out to
//! the reference `capnp convert binary:canonical` CLI and skips when the CLI
//! is not installed.

const std = @import("std");
const slcp = @import("slcp-core");

const capnpc = slcp.capnpc;
const canonical = slcp.canonical;
const crypto = slcp.crypto;
const qset = slcp.qset;
const gen_slcp = slcp.gen.slcp;

const Message = capnpc.message.Message;
const MessageBuilder = capnpc.message.MessageBuilder;
const json = std.json;

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn readVector(gpa: std.mem.Allocator, comptime name: []const u8) ?[]u8 {
    const io = std.testing.io;
    return std.Io.Dir.cwd().readFileAlloc(io, "vectors/" ++ name, gpa, .unlimited) catch null;
}

/// Parse a vector file into a json.Value on the arena, or null when absent
/// (caller turns null into error.SkipZigTest).
fn loadVector(arena: std.mem.Allocator, comptime name: []const u8) !?json.Value {
    const bytes = readVector(arena, name) orelse return null;
    return try json.parseFromSliceLeaky(json.Value, arena, bytes, .{});
}

fn field(v: json.Value, name: []const u8) json.Value {
    return v.object.get(name).?;
}

fn hexAlloc(gpa: std.mem.Allocator, s: []const u8) ![]u8 {
    const out = try gpa.alloc(u8, s.len / 2);
    const written = try std.fmt.hexToBytes(out, s);
    try std.testing.expectEqual(out.len, written.len);
    return out;
}

fn hexFixed(comptime n: usize, s: []const u8) ![n]u8 {
    var out: [n]u8 = undefined;
    try std.testing.expectEqual(@as(usize, n * 2), s.len);
    _ = try std.fmt.hexToBytes(&out, s);
    return out;
}

/// Straight through the library helpers: decodeFlat returns a FlatMessage
/// that owns its framed buffer (use-after-free fixed in src/canonical.zig).
fn sanityFlags(gpa: std.mem.Allocator, flat: []const u8) struct { decodes: bool, is_canonical: bool } {
    var fm = canonical.decodeFlat(gpa, flat, .{}) catch
        return .{ .decodes = false, .is_canonical = false };
    defer fm.deinit(gpa);
    return .{ .decodes = true, .is_canonical = capnpc.canonical.isCanonical(&fm.msg) };
}

/// Rebuild a wire QuorumSet message from a vector-file QS object
/// ({"threshold", "validators", "innerSets"}), absent pointers for empty lists.
fn buildQsFromValue(b: *gen_slcp.QuorumSet.Builder, v: json.Value) !void {
    try b.setThreshold(@intCast(field(v, "threshold").integer));
    const vals = field(v, "validators").array.items;
    if (vals.len > 0) {
        const vl = try b.initValidators(@intCast(vals.len));
        for (vals, 0..) |item, i| {
            const id = try hexFixed(32, item.string);
            try vl.set(@intCast(i), &id);
        }
    }
    const inners = field(v, "innerSets").array.items;
    if (inners.len > 0) {
        const il = try b.initInnerSets(@intCast(inners.len));
        for (inners, 0..) |item, i| {
            var ib = try il.get(@intCast(i));
            try buildQsFromValue(&ib, item);
        }
    }
}

fn qsFramedFromValue(gpa: std.mem.Allocator, v: json.Value) ![]const u8 {
    var mb = MessageBuilder.init(gpa);
    var root = try gen_slcp.QuorumSet.Builder.init(&mb);
    try buildQsFromValue(&root, v);
    return mb.toBytes();
}

/// The full receive pipeline on a vector input QS: wire build → validating
/// parse → fromReader → validateAndNormalize.
fn pipelineFromValue(gpa: std.mem.Allocator, v: json.Value) !qset.QuorumSetOwned {
    const framed = try qsFramedFromValue(gpa, v);
    var msg = try Message.init(gpa, framed, .{});
    const reader = try gen_slcp.QuorumSet.Reader.init(&msg);
    var owned = try qset.fromReader(gpa, reader);
    try qset.validateAndNormalize(gpa, &owned);
    return owned;
}

fn expectOwnedMatchesValue(owned: *const qset.QuorumSetOwned, v: json.Value) !void {
    try std.testing.expectEqual(@as(u32, @intCast(field(v, "threshold").integer)), owned.threshold);
    const vals = field(v, "validators").array.items;
    try std.testing.expectEqual(vals.len, owned.validators.len);
    for (vals, 0..) |item, i| {
        const id = try hexFixed(32, item.string);
        try std.testing.expectEqualSlices(u8, &id, &owned.validators[i]);
    }
    const inners = field(v, "innerSets").array.items;
    try std.testing.expectEqual(inners.len, owned.inner_sets.len);
    for (inners, 0..) |item, i| {
        try expectOwnedMatchesValue(&owned.inner_sets[i], item);
    }
}

// ---------------------------------------------------------------------------
// crypto.json
// ---------------------------------------------------------------------------

test "crypto vectors: networkIds, keys, gi replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "crypto.json")) orelse return error.SkipZigTest;

    for (field(root, "networkIds").array.items) |c| {
        const expected = try hexFixed(32, field(c, "networkId").string);
        const actual = crypto.networkIdFromPassphrase(field(c, "passphrase").string);
        try std.testing.expectEqualSlices(u8, &expected, &actual);
    }

    for (field(root, "keys").array.items) |c| {
        const seed = try hexFixed(32, field(c, "seed").string);
        const expected = try hexFixed(32, field(c, "publicKey").string);
        const actual = try crypto.publicKeyFromSeed(seed);
        try std.testing.expectEqualSlices(u8, &expected, &actual);
    }

    const gi_cases = field(root, "gi").array.items;
    try std.testing.expect(gi_cases.len >= 5);
    var tags_seen: [4]bool = @splat(false);
    for (gi_cases) |c| {
        const tag_int: u32 = @intCast(field(c, "tag").integer);
        const tag = std.enums.fromInt(crypto.GiTag, tag_int) orelse return error.UnknownGiTag;
        tags_seen[tag_int] = true;
        const slot: u64 = @intCast(field(c, "slot").integer);
        const round: u32 = @intCast(field(c, "round").integer);
        const prev = try hexAlloc(gpa, field(c, "prevValue").string);
        const m = try hexAlloc(gpa, field(c, "m").string);
        const expected = try std.fmt.parseInt(u64, field(c, "gi").string, 10);
        try std.testing.expectEqual(expected, crypto.gi(tag, slot, prev, round, m));
    }
    try std.testing.expect(tags_seen[1] and tags_seen[2] and tags_seen[3]);
}

test "crypto vectors: statement digest, signature, verify replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "crypto.json")) orelse return error.SkipZigTest;

    const statements = field(root, "statements").array.items;
    try std.testing.expect(statements.len >= 2);
    for (statements) |c| {
        const network_id = try hexFixed(32, field(c, "networkId").string);
        const seed = try hexFixed(32, field(c, "seed").string);
        const statement_bytes = try hexAlloc(gpa, field(c, "statementBytes").string);
        const expected_digest = try hexFixed(32, field(c, "digest").string);
        const expected_sig = try hexFixed(64, field(c, "signature").string);

        const digest = crypto.statementDigest(network_id, statement_bytes);
        try std.testing.expectEqualSlices(u8, &expected_digest, &digest);

        const sig = try crypto.sign(seed, digest);
        try std.testing.expectEqualSlices(u8, &expected_sig, &sig);

        const pk = try crypto.publicKeyFromSeed(seed);
        try std.testing.expect(crypto.verify(pk, digest, expected_sig));

        // statementBytes must themselves be canonical flat bytes.
        const flags = sanityFlags(gpa, statement_bytes);
        try std.testing.expect(flags.decodes);
        try std.testing.expect(flags.is_canonical);
    }
}

// ---------------------------------------------------------------------------
// qset.json
// ---------------------------------------------------------------------------

test "qset vectors: normalization cases replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "qset.json")) orelse return error.SkipZigTest;

    const cases = field(root, "cases").array.items;
    try std.testing.expect(cases.len >= 4);
    for (cases) |c| {
        var owned = try pipelineFromValue(gpa, field(c, "input"));
        try expectOwnedMatchesValue(&owned, field(c, "normalized"));
        const expected_hash = try hexFixed(32, field(c, "hash").string);
        const actual_hash = try qset.hashNormalized(gpa, &owned);
        try std.testing.expectEqualSlices(u8, &expected_hash, &actual_hash);
    }
}

test "qset vectors: rejections replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "qset.json")) orelse return error.SkipZigTest;

    const rejections = field(root, "rejections").array.items;
    try std.testing.expect(rejections.len >= 6);
    for (rejections) |c| {
        const expected_name = field(c, "error").string;
        if (pipelineFromValue(gpa, field(c, "input"))) |_| {
            std.debug.print("rejection case accepted: {s}\n", .{field(c, "name").string});
            return error.ExpectedRejection;
        } else |err| {
            try std.testing.expectEqualStrings(expected_name, @errorName(err));
        }
    }
}

// ---------------------------------------------------------------------------
// lint.json
// ---------------------------------------------------------------------------

test "lint vectors: findings replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "lint.json")) orelse return error.SkipZigTest;

    const cases = field(root, "cases").array.items;
    try std.testing.expect(cases.len >= 4);
    for (cases) |c| {
        var owned = try pipelineFromValue(gpa, field(c, "input"));
        const findings = try qset.lint(gpa, &owned);
        const expected = field(c, "findings").array.items;
        try std.testing.expectEqual(expected.len, findings.len);
        for (expected, findings) |e, f| {
            try std.testing.expectEqualStrings(field(e, "level").string, @tagName(f.level));
            try std.testing.expectEqualStrings(field(e, "code").string, @tagName(f.code));
            try std.testing.expectEqual(@as(u32, @intCast(field(e, "members").integer)), f.members);
            try std.testing.expectEqual(@as(u32, @intCast(field(e, "threshold").integer)), f.threshold);
        }
    }
}

// ---------------------------------------------------------------------------
// sanity.json (M0 partial: decode/canonicality level only)
// ---------------------------------------------------------------------------

test "sanity vectors: decode and canonicality flags replay" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "sanity.json")) orelse return error.SkipZigTest;

    const cases = field(root, "cases").array.items;
    try std.testing.expect(cases.len >= 4);
    for (cases) |c| {
        const flat = try hexAlloc(gpa, field(c, "flat").string);
        const flags = sanityFlags(gpa, flat);
        try std.testing.expectEqual(field(c, "decodes").bool, flags.decodes);
        try std.testing.expectEqual(field(c, "canonical").bool, flags.is_canonical);
    }
}

// ---------------------------------------------------------------------------
// Differential: our canonical bytes vs `capnp convert binary:canonical`
// (reference CLI; skips when capnp is not installed)
// ---------------------------------------------------------------------------

/// Run `capnp convert binary:canonical schema/slcp.capnp <type_name>` with
/// `framed_input` on stdin; returns the CLI's canonical (flat, table-less)
/// output bytes. Ported from capnp-zig tests/serialization/canonical_test.zig.
fn capnpConvertCanonical(
    gpa: std.mem.Allocator,
    input: []const u8,
    type_name: []const u8,
) ![]u8 {
    const io = std.testing.io;
    var child = std.process.spawn(io, .{
        .argv = &.{ "capnp", "convert", "binary:canonical", "schema/slcp.capnp", type_name },
        .stdin = .pipe,
        .stdout = .pipe,
        .stderr = .pipe,
    }) catch |err| switch (err) {
        error.FileNotFound => return error.SkipZigTest,
        else => return err,
    };

    try child.stdin.?.writeStreamingAll(io, input);
    child.stdin.?.close(io);
    child.stdin = null;

    var stdout_buf: [4096]u8 = undefined;
    var stdout_rdr = child.stdout.?.reader(io, &stdout_buf);
    const stdout_bytes = try stdout_rdr.interface.allocRemaining(gpa, .unlimited);

    var stderr_buf: [4096]u8 = undefined;
    var stderr_rdr = child.stderr.?.reader(io, &stderr_buf);
    const stderr_bytes = try stderr_rdr.interface.allocRemaining(gpa, .unlimited);

    const term = try child.wait(io);
    switch (term) {
        .exited => |code| {
            if (code != 0) {
                std.debug.print("capnp convert failed: {s}\n", .{stderr_bytes});
                return error.CapnpConvertFailed;
            }
        },
        else => {
            std.debug.print("capnp convert failed: unexpected termination\n", .{});
            return error.CapnpConvertFailed;
        },
    }
    return stdout_bytes;
}

test "differential: statement canonical bytes match capnp convert binary:canonical" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "crypto.json")) orelse return error.SkipZigTest;

    const statements = field(root, "statements").array.items;
    for (statements) |c| {
        const flat = try hexAlloc(gpa, field(c, "statementBytes").string);
        const framed = try canonical.frameFlat(gpa, flat);

        // Reference CLI canonicalization of the same framed message must
        // reproduce our flat bytes exactly (they are already canonical).
        const cli = try capnpConvertCanonical(gpa, framed, "Statement");
        try std.testing.expectEqualSlices(u8, flat, cli);

        // ... and our own canonicalizer agrees with itself round-tripped.
        const ours = try canonical.canonicalFlatFromFramed(gpa, framed);
        try std.testing.expectEqualSlices(u8, flat, ours);
    }
}

test "differential: qset canonical bytes match capnp convert binary:canonical" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const gpa = arena_state.allocator();
    const root = (try loadVector(gpa, "qset.json")) orelse return error.SkipZigTest;

    // Use every normalization case's INPUT message (non-normalized wire
    // shapes included): the differential is about canonicalization, and the
    // reference CLI must agree on each of them.
    const cases = field(root, "cases").array.items;
    for (cases) |c| {
        const framed = try qsFramedFromValue(gpa, field(c, "input"));
        const ours = try canonical.canonicalFlatFromFramed(gpa, framed);
        const cli = try capnpConvertCanonical(gpa, framed, "QuorumSet");
        try std.testing.expectEqualSlices(u8, ours, cli);
    }
}
